# Generated by Django 5.0.4 on 2025-03-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='openai_vs_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
