# Generated by Django 5.0.4 on 2025-03-16 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_projectfile_openai_vs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfile',
            old_name='openai_vs_id',
            new_name='vector_store_id',
        ),
    ]
