# Generated by Django 5.0.4 on 2025-03-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_rename_openai_vs_id_projectfile_vector_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='vector_store_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
